name: Windows Test

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run build
      - run: npm run karmaEdge
      - run: npm run karmaChrome
